theme = {
    "fontFamily": "Raleway",
    "title_standoff": 15,
    "tickfont_size": 15,
    "titlefont_size": 15,
}

yellow = "#FFCB08"
blue = "#0075BB"
red = "#B81E23"

colors = {"background": "#111111", "text": "black", "title": red, "cardName": "black"}
card_style = {"margin": "0.5rem 0.5rem 0.5rem 0.5rem", "background": "white"}

organisation_colors = {
    "USA": "rgb(186, 12, 47)",
    "NATO": "rgb(72, 72, 72)",
    "EU": "rgb(255, 214, 23)",
    "UN": "rgb(91, 146, 229)",
    "OSCE": "rgb(5, 102, 8)",
    "MFO": "rgb(220, 107, 49)",
    "default": "rgb(0, 0, 139)",
    "Other": "rgb(34, 139, 34)",
}

country_colors = {
    "CZE": "rgb(171,73,42)",
    "NZL": "rgb(0,61,90)",
    "GBR": "rgb(87,0,0)",
    "SVK": "rgb(94,88,159)",
    "LUX": "rgb(104,69,0)",
    "MKD": "rgb(0,48,39)",
    "BEL": "rgb(137,128,203)",
    "POL": "rgb(0,27,51)",
    "NOR": "rgb(154,8,46)",
    "GRC": "rgb(21,21,21)",
    "SVN": "rgb(130,164,253)",
    "ITA": "rgb(190,142,8)",
    "MNE": "rgb(255,203,163)",
    "EST": "rgb(128,209,194)",
    "LVA": "rgb(224,118,83)",
    "NLD": "rgb(54,52,118)",
    "HRV": "rgb(86,167,152)",
    "ALB": "rgb(40,124,111)",
    "TUR": "rgb(146,105,0)",
    "DEU": "rgb(231,93,105)",
    "AUS": "rgb(69,34,0)",
    "ROU": "rgb(255,232,107)",
    "DNK": "rgb(242,188,64)",
    "ESP": "rgb(255,192,198)",
    "CAN": "rgb(8,20,80)",
    "BGR": "rgb(30,135,167)",
    "USA": "rgb(196,61,77)",
    "LTU": "rgb(1,86,75)",
    "HUN": "rgb(133,220,255)",
    "FRA": "rgb(4,56,130)",
    "JPN": "rgb(178,209,255)",
    "PRT": "rgb(177,166,245)",
    "KOR": "rgb(88,179,212)",
    "default": "rgb(53,53,53)",
}

country_regions = {
    "CZE": "Eastern Europe",
    "NZL": "Australia and New Zealand",
    "GBR": "Northern Europe",
    "SVK": "Eastern Europe",
    "LUX": "Western Europe",
    "MKD": "Southern Europe",
    "BEL": "Western Europe",
    "POL": "Eastern Europe",
    "NOR": "Northern Europe",
    "GRC": "Southern Europe",
    "SVN": "Southern Europe",
    "ITA": "Southern Europe",
    "MNE": "Southern Europe",
    "EST": "Northern Europe",
    "LVA": "Northern Europe",
    "NLD": "Western Europe",
    "HRV": "Southern Europe",
    "ALB": "Southern Europe",
    "TUR": "Western Asia",
    "DEU": "Western Europe",
    "AUS": "Australia and New Zealand",
    "ROU": "Eastern Europe",
    "DNK": "Northern Europe",
    "ESP": "Southern Europe",
    "CAN": "Northern America",
    "BGR": "Eastern Europe",
    "USA": "Northern America",
    "LTU": "Northern Europe",
    "HUN": "Eastern Europe",
    "FRA": "Western Europe",
    "JPN": "Eastern Asia",
    "PRT": "Southern Europe",
    "KOR": "Eastern Asia",
    "default": "N/A",
}

country_codes = {
    "AFG": "Afghanistan",
    "ALA": "Aland Islands",
    "ALB": "Albania",
    "DZA": "Algeria",
    "ASM": "American Samoa",
    "AND": "Andorra",
    "AGO": "Angola",
    "AIA": "Anguilla",
    "ATA": "Antarctica",
    "ATG": "Antigua and Barbuda",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ABW": "Aruba",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BHS": "Bahamas",
    "BHR": "Bahrain",
    "BGD": "Bangladesh",
    "BRB": "Barbados",
    "BLR": "Belarus",
    "BEL": "Belgium",
    "BLZ": "Belize",
    "BEN": "Benin",
    "BMU": "Bermuda",
    "BTN": "Bhutan",
    "BOL": "Bolivia",
    "BIH": "Bosnia and Herzegovina",
    "BWA": "Botswana",
    "BVT": "Bouvet Island",
    "BRA": "Brazil",
    "VGB": "British Virgin Islands",
    "IOT": "British Indian Ocean Territory",
    "BRN": "Brunei Darussalam",
    "BGR": "Bulgaria",
    "BFA": "Burkina Faso",
    "BDI": "Burundi",
    "KHM": "Cambodia",
    "CMR": "Cameroon",
    "CAN": "Canada",
    "CPV": "Cape Verde",
    "CYM": "Cayman Islands",
    "CAF": "Central African Republic",
    "TCD": "Chad",
    "CHL": "Chile",
    "CHN": "China",
    "HKG": "Hong Kong, Special Administrative Region of China",
    "MAC": "Macao, Special Administrative Region of China",
    "CXR": "Christmas Island",
    "CCK": "Cocos (Keeling) Islands",
    "COL": "Colombia",
    "COM": "Comoros",
    "COG": "Congo (Brazzaville)",
    "COD": "Democratic Republic of the Congo",
    "COK": "Cook Islands",
    "CRI": "Costa Rica",
    "CIV": "Cote d'Ivoire",
    "HRV": "Croatia",
    "CUB": "Cuba",
    "CYP": "Cyprus",
    "CZE": "Czech Republic",
    "DNK": "Denmark",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "SLV": "El Salvador",
    "GNQ": "Equatorial Guinea",
    "ERI": "Eritrea",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "FLK": "Falkland Islands (Malvinas)",
    "FRO": "Faroe Islands",
    "FJI": "Fiji",
    "FIN": "Finland",
    "FRA": "France",
    "GUF": "French Guiana",
    "PYF": "French Polynesia",
    "ATF": "French Southern Territories",
    "GAB": "Gabon",
    "GMB": "Gambia",
    "GEO": "Georgia",
    "DEU": "Germany",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GRC": "Greece",
    "GRL": "Greenland",
    "GRD": "Grenada",
    "GLP": "Guadeloupe",
    "GUM": "Guam",
    "GTM": "Guatemala",
    "GGY": "Guernsey",
    "GIN": "Guinea",
    "GNB": "Guinea-Bissau",
    "GUY": "Guyana",
    "HTI": "Haiti",
    "HMD": "Heard Island and Mcdonald Islands",
    "VAT": "Holy See (Vatican City State)",
    "HND": "Honduras",
    "HUN": "Hungary",
    "ISL": "Iceland",
    "IND": "India",
    "IDN": "Indonesia",
    "IRN": "Islamic Republic of Iran",
    "IRQ": "Iraq",
    "IRL": "Ireland",
    "IMN": "Isle of Man",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JPN": "Japan",
    "JEY": "Jersey",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KIR": "Kiribati",
    "PRK": "Democratic People's Republic of Korea",
    "KOR": "Republic of Korea",
    "KWT": "Kuwait",
    "KGZ": "Kyrgyzstan",
    "LAO": "Lao PDR",
    "LVA": "Latvia",
    "LBN": "Lebanon",
    "LSO": "Lesotho",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LIE": "Liechtenstein",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "MKD": "Republic of Macedonia",
    "MDG": "Madagascar",
    "MWI": "Malawi",
    "MYS": "Malaysia",
    "MDV": "Maldives",
    "MLI": "Mali",
    "MLT": "Malta",
    "MHL": "Marshall Islands",
    "MTQ": "Martinique",
    "MRT": "Mauritania",
    "MUS": "Mauritius",
    "MYT": "Mayotte",
    "MEX": "Mexico",
    "FSM": "Federated States of Micronesia",
    "MDA": "Moldova",
    "MCO": "Monaco",
    "MNG": "Mongolia",
    "MNE": "Montenegro",
    "MSR": "Montserrat",
    "MAR": "Morocco",
    "MOZ": "Mozambique",
    "MMR": "Myanmar",
    "NAM": "Namibia",
    "NRU": "Nauru",
    "NPL": "Nepal",
    "NLD": "Netherlands",
    "ANT": "Netherlands Antilles",
    "NCL": "New Caledonia",
    "NZL": "New Zealand",
    "NIC": "Nicaragua",
    "NER": "Niger",
    "NGA": "Nigeria",
    "NIU": "Niue",
    "NFK": "Norfolk Island",
    "MNP": "Northern Mariana Islands",
    "NOR": "Norway",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PLW": "Palau",
    "PSE": "Palestinian Territory, Occupied",
    "PAN": "Panama",
    "PNG": "Papua New Guinea",
    "PRY": "Paraguay",
    "PER": "Peru",
    "PHL": "Philippines",
    "PCN": "Pitcairn",
    "POL": "Poland",
    "PRT": "Portugal",
    "PRI": "Puerto Rico",
    "QAT": "Qatar",
    "REU": "Reunion",
    "ROU": "Romania",
    "RUS": "Russian Federation",
    "RWA": "Rwanda",
    "BLM": "Saint-Barthelemy",
    "SHN": "Saint Helena",
    "KNA": "Saint Kitts and Nevis",
    "LCA": "Saint Lucia",
    "MAF": "Saint-Martin (French part)",
    "SPM": "Saint Pierre and Miquelon",
    "VCT": "Saint Vincent and Grenadines",
    "WSM": "Samoa",
    "SMR": "San Marino",
    "STP": "Sao Tome and Principe",
    "SAU": "Saudi Arabia",
    "SEN": "Senegal",
    "SRB": "Serbia",
    "SYC": "Seychelles",
    "SLE": "Sierra Leone",
    "SGP": "Singapore",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SLB": "Solomon Islands",
    "SOM": "Somalia",
    "ZAF": "South Africa",
    "SGS": "South Georgia and the South Sandwich Islands",
    "SSD": "South Sudan",
    "ESP": "Spain",
    "LKA": "Sri Lanka",
    "SDN": "Sudan",
    "SUR": "Suriname",
    "SJM": "Svalbard and Jan Mayen Islands",
    "SWZ": "Swaziland",
    "SWE": "Sweden",
    "CHE": "Switzerland",
    "SYR": "Syrian Arab Republic (Syria)",
    "TWN": "Republic of China Taiwan",
    "TJK": "Tajikistan",
    "TZA": "United Republic of Tanzania",
    "THA": "Thailand",
    "TLS": "Timor-Leste",
    "TGO": "Togo",
    "TKL": "Tokelau",
    "TON": "Tonga",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TKM": "Turkmenistan",
    "TCA": "Turks and Caicos Islands",
    "TUV": "Tuvalu",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "ARE": "United Arab Emirates",
    "GBR": "United Kingdom",
    "USA": "United States",
    "UMI": "United States Minor Outlying Islands",
    "URY": "Uruguay",
    "UZB": "Uzbekistan",
    "VUT": "Vanuatu",
    "VEN": "Venezuela",
    "VNM": "Viet Nam",
    "VIR": "Virgin Islands, US",
    "WLF": "Wallis and Futuna Islands",
    "ESH": "Western Sahara",
    "YEM": "Yemen",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe",
}

eu_countries = [
    "UKR",
    "FRA",
    "ESP",
    "SWE",
    "DEU",
    "FIN",
    "NOR",
    "POL",
    "ITA",
    "GBR",
    "ROU",
    "BLR",
    "GRC",
    "BGR",
    "ISL",
    "PRT",
    "CZE",
    "DNK",
    "HUN",
    "SRB",
    "AUT",
    "IRL",
    "LTU",
    "LVA",
    "HRV",
    "BIH",
    "SVK",
    "EST",
    "NLD",
    "CHE",
    "MDA",
    "BEL",
    "ALB",
    "MKD",
    "SVN",
    "MNE",
    "CYP",
    "LUX",
    "FRO",
    "AND",
    "MLT",
    "LIE",
    "GGY",
    "SMR",
    "GIB",
    "MCO",
    "VAT",
]
nato_countries = [
    "ALB",
    "BEL",
    "BGR",
    "CAN",
    "HRV",
    "CZE",
    "DNK",
    "EST",
    "FRA",
    "DEU",
    "GRC",
    "HUN",
    "ISL",
    "ITA",
    "LVA",
    "LTU",
    "LUX",
    "MNE",
    "NLD",
    "MKD",
    "NOR",
    "POL",
    "PRT",
    "ROU",
    "SVK",
    "SVN",
    "ESP",
    "TUR",
    "GBR",
    "USA",
]
